#!/usr/bin/env bash

set -euo pipefail

TARGET_DIR="${1:-}"
PROJECT_NAME="${2:-}"

if [[ -z "$TARGET_DIR" ]]; then
  echo "Usage: setup.sh <absolute-project-dir> [project-name]" >&2
  exit 1
fi

if [[ "$TARGET_DIR" != /* ]]; then
  echo "Error: please provide an absolute project directory path." >&2
  exit 1
fi

if [[ "$TARGET_DIR" == "/" ]]; then
  echo "Error: target directory cannot be root (/)." >&2
  exit 1
fi

if [[ -z "$PROJECT_NAME" ]]; then
  PROJECT_NAME="$(basename "$TARGET_DIR")"
fi
PROJECT_NAME="${PROJECT_NAME//$'\n'/ }"
PROJECT_NAME="${PROJECT_NAME//$'\r'/ }"

mkdir -p "$TARGET_DIR/src"

cat > "$TARGET_DIR/README.md" <<EOF
{
  printf '# %s\n\n' "$PROJECT_NAME"
  printf 'Generated by DeerFlow project-builder skill.\n\n'
  printf '## Quick Start\n\n'
  printf '1. Fill environment values in `.env` (copy from `.env.example`).\n'
  printf '2. Implement project logic in `src/`.\n'
  printf '3. Run your framework build/test commands.\n'
  printf '4. Push to Git and deploy.\n'
} > "$TARGET_DIR/README.md"

cat > "$TARGET_DIR/.gitignore" <<'EOF'
node_modules/
.venv/
dist/
build/
.next/
coverage/
.DS_Store
.env
EOF

cat > "$TARGET_DIR/.env.example" <<'EOF'
# Business API
BUSINESS_API_BASE_URL=
BUSINESS_API_TOKEN=

# Git
GIT_REMOTE_URL=

# Deployment
VERCEL_TOKEN=
EOF

cat > "$TARGET_DIR/src/main.txt" <<'EOF'
Project scaffold initialized. Replace with your generated application code.
EOF

echo "✅ Project scaffold created at $TARGET_DIR"
